"""Add installer_category to User

Revision ID: 0217e0c1e068
Revises: 3ce796503bb4
Create Date: 2025-10-26 21:07:09.286229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0217e0c1e068'
down_revision = '3ce796503bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installer_category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('installer_category')

    # ### end Alembic commands ###
