"""Add text summary fields to analysis result

Revision ID: 5b4399679710
Revises: 2fd5d0af8d08
Create Date: 2025-10-28 00:12:25.895062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4399679710'
down_revision = '2fd5d0af8d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('financial_summary_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('environmental_summary_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('environmental_summary_text')
        batch_op.drop_column('financial_summary_text')
        batch_op.drop_column('summary_text')

    # ### end Alembic commands ###
