"""Add contract_accepted to User

Revision ID: 6b205349bd28
Revises: 31baf6266495
Create Date: 2025-10-27 00:05:50.489132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b205349bd28'
down_revision = '31baf6266495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_accepted', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contract_accepted')

    # ### end Alembic commands ###
