"""Add solar suitability score to analysis result

Revision ID: 9e64ce4b2d85
Revises: 5b4399679710
Create Date: 2025-10-28 00:49:04.384396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e64ce4b2d85'
down_revision = '5b4399679710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solar_suitability_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('solar_suitability_score')

    # ### end Alembic commands ###
