"""Initial migration without OTP

Revision ID: aeabc5673afb
Revises: 
Create Date: 2025-10-25 12:38:29.614941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeabc5673afb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_name'), ['name'], unique=False)

    op.create_table('finance_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('loan_terms', sa.String(), nullable=True),
    sa.Column('interest_rate', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_partners_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_partners_name'), ['name'], unique=False)

    op.create_table('installers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('service_areas', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installers_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_installers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_installers_id'), ['id'], unique=False)

    op.create_table('solar_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('avg_sun_hours', sa.Float(), nullable=True),
    sa.Column('panel_efficiency', sa.Float(), nullable=True),
    sa.Column('irradiance_kwm2', sa.Float(), nullable=True),
    sa.Column('avg_temp', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solar_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solar_data_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_solar_data_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_id'), ['id'], unique=False)

    op.create_table('installer_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['installer_id'], ['installers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installer_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installer_reviews_id'), ['id'], unique=False)

    op.create_table('leaderboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_savings', sa.Float(), nullable=True),
    sa.Column('total_co2_reduced', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboards_id'), ['id'], unique=False)

    op.create_table('roof_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('roof_type', sa.String(), nullable=True),
    sa.Column('monthly_bill', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('solar_score', sa.Float(), nullable=True),
    sa.Column('system_size_kw', sa.Float(), nullable=True),
    sa.Column('install_cost', sa.Float(), nullable=True),
    sa.Column('annual_savings', sa.Float(), nullable=True),
    sa.Column('roi_years', sa.Float(), nullable=True),
    sa.Column('co2_saved', sa.Float(), nullable=True),
    sa.Column('report_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roof_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roof_analyses_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_roof_analyses_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roof_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roof_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_roof_analyses_address'))

    op.drop_table('roof_analyses')
    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboards_id'))

    op.drop_table('leaderboards')
    with op.batch_alter_table('installer_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installer_reviews_id'))

    op.drop_table('installer_reviews')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('solar_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solar_data_id'))
        batch_op.drop_index(batch_op.f('ix_solar_data_county'))

    op.drop_table('solar_data')
    with op.batch_alter_table('installers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installers_id'))
        batch_op.drop_index(batch_op.f('ix_installers_email'))
        batch_op.drop_index(batch_op.f('ix_installers_company_name'))

    op.drop_table('installers')
    with op.batch_alter_table('finance_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_partners_name'))
        batch_op.drop_index(batch_op.f('ix_finance_partners_id'))

    op.drop_table('finance_partners')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_name'))
        batch_op.drop_index(batch_op.f('ix_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_email'))

    op.drop_table('admin')
    # ### end Alembic commands ###
