"""Add roof_model_url to AnalysisResult

Revision ID: d7133b034d22
Revises: 24a787fcdc1b
Create Date: 2025-10-26 16:11:00.284727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7133b034d22'
down_revision = '24a787fcdc1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roof_model_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('roof_model_url')

    # ### end Alembic commands ###
